[package]
name = "waffle"
version = "0.1.0"
authors = ["Ivan Yakushev <iamaero7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
